### PR TITLE
fix: Separate RHCOS and OCP versions

### PR DESCRIPTION
**Pull request by smolin-de**
This patch provides the user the ability to specify the OCP and the RHCOS version separately.

### CODE REVIEW

**Comment by smolin-de** [comment]
FYI
@AmadeusPodvratnik

**Review by AmadeusPodvratnik — COMMENTED** [review]
@smolin-de even it's somehow cumbersome I would integrate the documentation to this PR. Documentation is not that much and saves another PR only for documentation. Code changes looking good to me.

**Review by AmadeusPodvratnik — COMMENTED** [review]
@smolin-de Thx for adding the doc to the PR. I would suggest to remove the "Feel free...." because this not the case for other parameters. In addition I would write "Link to the CoreOS files..." and not mention mirror because you can configure any valid URL.

**Comment by smolin-de** [comment]
@AmadeusPodvratnik 
I added the suggested changes.

**Review by AmadeusPodvratnik — APPROVED** [review]
Thank you. I'm good with those changes.

**Pull request merged**
