### PR TITLE
feat: Add support for fips and some minor code allignments

### PR DESCRIPTION
**Pull request by AmadeusPodvratnik**
This is the support for fips in Agend-based Installer (ABI).
And solves issue #305.
In addition some minor code changes based on ansible-lint.

### CODE REVIEW

**Comment by AmadeusPodvratnik** [comment]
@veera-damisetti @isumitsolanki pls review this PR. Thank you ...

**Comment by veera-damisetti** [comment]
@AmadeusPodvratnik 
I already had a look and looks good to me 
@isumitsolanki can also review this , as this is related to ABI

**Review by isumitsolanki — APPROVED** [review]
Hi @AmadeusPodvratnik , looks good to me.

**Pull request merged**
