### PR TITLE
fix: Update Bastion DNS entries only when enabled

### PR DESCRIPTION
**Pull request by smolin-de**
Update Bastion DNS entries only when enabled.

### CODE REVIEW

**Review by AmadeusPodvratnik — COMMENTED** [review]
Hi @smolin-de, I discovered issues with undefined vars. Makes it sens to have a "is defined" check, too?

**Comment by AmadeusPodvratnik** [comment]
> > Hi @smolin-de, I discovered issues with undefined vars. Makes it sens to have a "is defined" check, too?
> 
> Hi, env.bastion.options.dns is a defined variable in the all.yaml.template file. It must be defined. Either 'true' or 'false'. If the variable is not defined, do we assume bastion host supports dns or not ?

I would say that DNS is being supported if set to true all other values (include not define) will be taken as not supported.

**Review by jacobemery — APPROVED** [review]
LGTM

**Pull request merged**
