### PR TITLE
BREAKING CHANGE: overhaul variables

### PR DESCRIPTION
**Pull request by jacobemery**
- Long overdue complete overhaul of how variables are structured and used.
- Variables structure better aligned with Ansible best practices, allowing for greater flexibility, simplicity and scaling.
- Restructured the documentation for better organization and added pictures.
- Created setup scripts to install required software (like Ansible itself) - #161

- Re-worked many playbooks as a result of variables overhaul leading to various optimizations, including:
    - Ability to allocate VM guests to specific hosts, using their 'guests' list in inventory
    - Ability to add/delete as many compute nodes as you want
    - Enablement Ansible Vault to protect sensitive variables
    - Ability to create as many LPARs as you want
    - Ability to attach as many Storage Groups and Network Interface Cards to those LPARs as you want
    - Ability to have as many hypervisors hosting VMs as you want
    - Separation of OpenVPN from high availability #118 
    - Fix proxy vars indent #122  
    - Clarify virtual network definitions in docs and create variable for interface #163
    - Document storage pool_path #155
    - And more...

- My apologies this is such a huge Pull Request, the variables overhaul required almost everything to change, not just references to variables, but how they are referenced, loops, etc.

- @veera-damisetti I wasn't 100% sure on a lot of the HyperShift changes I made, but I believe the create_inventory_setup_hypershift is no longer required because of the inventory change, and creation of secrets.yaml is no longer required because of the Ansible Vault. But please double-check me here, as I'm much less familiar with your work.

- I'm opening this on the 'development' branch because I'm sure changes will need to be made and I'd love as many eyes on this as possible so we can get as much of the variables right as possible all in one breaking change
cc @AmadeusPodvratnik 
cc @smolin-de 
cc @ryoung1us
cc @irmsan

### CODE REVIEW

**Comment by smolin-de** [comment]
@jacobemery 
The development branch is 27 commits behind main branch. Your PR contains changes which are already in the main branch and includes some conflicts. Please create a PR with only new changes. This would reduce the number of changes to review.

**Comment by jacobemery** [comment]
Good point, I'll open a new PR with that fixed.

**Comment by jacobemery** [comment]
@veera-damisetti yes let's merge your PR first.

**Comment by jacobemery** [comment]
Resolved merge conflicts and opened new [PR](https://github.com/IBM/Ansible-OpenShift-Provisioning/pull/178)

**Pull request closed without merging**
