### PR TITLE
feat: OCPONZ-4396 Automation of ISO boot support for KVM

### PR DESCRIPTION
**Pull request by sanjayy-ibm**
New Parameter: Introduced a new parameter boot_method to support both PXE and ISO-based installations.
ISO Image Creation: Added functionality for ISO image creation for KVM.
ISO-Based Installation: Implemented support for installations using ISO images.
Cleanup on Cluster Deletion: Added a cleanup process to remove the ISO install media during cluster deletion when boot_method is set to ISO.

### CODE REVIEW

**Comment by veera-damisetti** [comment]
Discussed with @sanjayy-ibm  offline  for the required changes

**Comment by sanjayy-ibm** [comment]
Summary of Changes
**New Parameter**: Introduced a new parameter `boot_method `to support both PXE and ISO-based installations.
**ISO Image Creation**: Added functionality for ISO image creation for KVM.
**ISO-Based Installation**: Implemented support for installations using ISO images.
**Cleanup on Cluster Deletion**: Added a cleanup process to remove the ISO install media during cluster deletion when boot_method is set to ISO.

**Comment by veera-damisetti** [comment]
Looks good 
cc: @AmadeusPodvratnik

**Review by veera-damisetti — APPROVED** [review]

**Pull request merged**
