### PR TITLE
Support for disconnected cluster installation using ABI on kvm

### PR DESCRIPTION
**Pull request by isumitsolanki**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Not directly related to this pr but I see you have a role called prepare_config which is only used for abi. Maybe at some point rename this so we know its for abi or perhaps we can figure out a way to generalize the mirroring operations better so we can reuse them everywhere instead of duplication.

We don't have to fix this now but food for thought.

**Comment by isumitsolanki** [comment]
Hi @mohammedzee1000 , sure

**Review by AmadeusPodvratnik — APPROVED** [review]
Hi @isumitsolanki, thx for the PR. /lgtm

**Pull request merged**
