### PR TITLE
chore: Increase 'approve_certs' wait time to 45 min

### PR DESCRIPTION
**Pull request by smolin-de**
Approve certificate wait time is increased to 45min.

### CODE REVIEW

**Review by AmadeusPodvratnik — COMMENTED** [review]
Hi @smolin-de Thank you for the PR. Just a question about these wait times. Make a configurable value sense?

**Comment by smolin-de** [comment]
> Hi @smolin-de Thank you for the PR. Just a question about these wait times. Make a configurable value sense?

I do not think that an configurable value make sense.
The install will fail, if the time is to small.

**Review by AmadeusPodvratnik — APPROVED** [review]
@smolin-de Thank you ... /lgtm

**Pull request merged**
