### PR TITLE
Make pkgs vars default

### PR DESCRIPTION
**Pull request by AmadeusPodvratnik**
Remove packages (env.pkgs.) from all.yaml.template and use defaults instead.

### CODE REVIEW

**Comment by AmadeusPodvratnik** [comment]
@veera-damisetti Pls review this PR. I don't know why I picked up that amount of commits but nevertheless the PR is good to go. The packages parameters are removed and substituted with default values. Nevertheless user could add specific pkgs_xxx to all.yaml file. The documentation is updated accordingly.

**Comment by veera-damisetti** [comment]
@isumitsolanki  shall we sync offline and review this PR  
thanks

**Comment by isumitsolanki** [comment]
@veera-damisetti sure , we'll do in sometime.

**Comment by isumitsolanki** [comment]
@AmadeusPodvratnik , @veera-damisetti , Looks good to me.

**Pull request merged**
