### PR TITLE
feat: Add support to create a three node OCP cluster

### PR DESCRIPTION
**Pull request by smolin-de**
With this patch you can create a three node OCP cluster, without dedicated compute nodes. You just need to uncomment the compute node hostname definition in the config file (all.yaml).

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
This is pretty cool. 
Although one questions, what do you mean by 'uncomment the compute node host name definition'. Isnt compute node section uncommented by default

https://github.com/IBM/Ansible-OpenShift-Provisioning/blob/b440fe5d4380199713ed10b7c36fa96a768afa69/inventories/default/group_vars/all.yaml.template#L135-L152

**Comment by smolin-de** [comment]
> This is pretty cool. Although one questions, what do you mean by 'uncomment the compute node host name definition'? Isn't compute node section uncommented by default?
> 
> https://github.com/IBM/Ansible-OpenShift-Provisioning/blob/b440fe5d4380199713ed10b7c36fa96a768afa69/inventories/default/group_vars/all.yaml.template#L135-L152

You are right. We do not need to uncomment compute node definition, when my patch is applied. It is the default value. I forgot it, because with the current code you must define compute nodes.

**Review by AmadeusPodvratnik — COMMENTED** [review]
Hi @smolin-de , thank you for this PR. Very cool and one step closer to SNO. Nevertheless I have a question regarding different AOP runs. For example someone is testing your 3 Node cluster and next it would like to test a 5 node cluster (or vice versa). How the correct haproxy settings will be exchanged? What steps the user need to be followed?
Due to the fact that this is an 'implicit' feature only handled by setting some variables, I would suggest to document this feature. Maybe it's worth to start a table documenting the features we support (similar we track internally using mural).

**Review by AmadeusPodvratnik — APPROVED** [review]
@smolin-de Thank you.

**Pull request merged**
