### PR TITLE
Enhancement: Updated conditions for LPAR HCP

### PR DESCRIPTION
**Pull request by veera-damisetti**
Updated conditions for LPAR HCP

### CODE REVIEW

**Review by AmadeusPodvratnik — CHANGES_REQUESTED** [review]
@veera-damisetti Thank you for the PR. Due to the fact that ansible-lint is checking the code style etc., it complains about the missing FQCN for builtin module actions. For cleaning up the code it is necessary to use e.g. ansible.builtin.include_tasks instead only include_tasks.
Pls use the ansible-lint to check your code.

**Comment by veera-damisetti** [comment]
Sure @AmadeusPodvratnik 
will check with ansible-lint

**Comment by veera-damisetti** [comment]
I have changed to use ansible.builtin.include_task or ansible.builtin.include_role

**Comment by veera-damisetti** [comment]
Running ansible-lint is giving lot of errors accross all the roles .
Shall we do it in this PR only or shall we do it seperate for other files

**Comment by AmadeusPodvratnik** [comment]
> Running ansible-lint is giving lot of errors accross all the roles . Shall we do it in this PR only or shall we do it seperate for other files
It depends on how many changes need to be made. I would say not to push that much .. if you want you can do some (otherwise it will be done step by step).

**Comment by veera-damisetti** [comment]
Sure @AmadeusPodvratnik 
I did changes in current file changes as per ansible lint , and yes we should cover everything , going forward

**Review by AmadeusPodvratnik — CHANGES_REQUESTED** [review]
@veera-damisetti Thank you for the PR. /lgtm

**Review by AmadeusPodvratnik — APPROVED** [review]

**Pull request merged**
