### PR TITLE
fix: Update HAProxy.cfg during day-2 compute node install

### PR DESCRIPTION
**Pull request by smolin-de**
This patch updates the HAProxy.cfg file during compute node install and removal.

### CODE REVIEW

**Comment by smolin-de** [comment]
This patch resolves issue #223

**Review by AmadeusPodvratnik — COMMENTED** [review]
Hi @smolin-de, thx for the PR. I have following questions:
- Why you are opening 1936 for tcp on the firewall?
- You add haproxy role to reinstall cluster and for day2 operations but in the general flow the haproxy is configured during 5_setup_bastion playbook. So for reinstall cluster nothing should change or am I wrong.

**Comment by smolin-de** [comment]
> Hi @smolin-de, thx for the PR. I have following questions:
> 
>     * Why you are opening 1936 for tcp on the firewall?
> 
>     * You add haproxy role to reinstall cluster and for day2 operations but in the general flow the haproxy is configured during 5_setup_bastion playbook. So for reinstall cluster nothing should change or am I wrong.


Q -  Why you are opening 1936 for tcp on the firewall?
A - The current HAProxy config file uses port 1936 to access HAProxy statistics, but this port is not enabled in the firewall.
      I enabled the port to access HAProxy statistics.  But, it is not required for the fix. We could or should create a separate patch for the port issue. I will remove the fort change from this patch.
 
 Q - You add haproxy role to reinstall cluster and for day2 operations but in the general flow the haproxy is configured during 5_setup_bastion playbook. So for reinstall cluster nothing should change or am I wrong.
A - If you install a cluster and add day-2 compute nodes, then your HAproxy config will contain all compute nodes. If you now reinstall the cluster and want to have a different day-2 setup, then you run into an issue. Because, the HAProxy config file contains the old setup with the old day-2 compute nodes. Therefore, I am resetting the HAProxy config file to the default setup without day-2 compute node entries.

**Review by AmadeusPodvratnik — APPROVED** [review]
Thank you ... looks good.

**Pull request merged**
