### PR TITLE
feat: Untrack all.yaml file in git

### PR DESCRIPTION
**Pull request by smolin-de**
The inventory file 'all.yaml' is part of the current git structure. This file is always modifed to execute Ansible-OpenShift-Provisioning and therefore it will be tracked in your git branch as modifed. But, it will not be commited, because it contains credentials !

This patch renames the original file to a template filename. The user needs to create a local 'all.yaml' copy.

Signed-off-by: Klaus Smolin <SMOLIN@de.ibm.com>

### CODE REVIEW

**Comment by smolin-de** [comment]
> Definitely agree on adding all.yaml to untrack git files.
> 
> What is your reasoning for the template for all.yaml? Just to have a clean copy if they need to start fresh? Maybe instead of requiring them to create a local copy, we just create a clean backup for them instead. That way it's one less step right at the beginning.
> 
> What do you think @smolin-de ?

> What is your reasoning for the template for all.yaml?
all.yaml is part of the git and it must be modified. I have always uncommitted git changes. When I work with other git branches, then I need to stage my changes locally or delete the all.yaml file. I need be very careful to not accidentally push my changes to the git tree where everybody can see them, because all.yaml contains some of my private credentials
I just want that my config file (with credentials) is not part of the got tree.

**Review by jacobemery — COMMENTED** [review]
> I need be very careful to not accidentally push my changes to the git tree

Ah I see. I figured there'd be a way to ignore future changes to a file with GitHub, but I'm not finding one. This sounds like a fine workaround.

It does add a step at the beginning, but that's better than accidentally exposing credentials. Plus, this will prime users to think about the names of the inventory files for when they will have to change the name(s) of the KVM host inventory files as well.

I'll have to add a short step to the docs as well. Let me get that ready so I can push that and merge this at relatively the same time.

**Comment by jacobemery** [comment]
Added documentation, good to merge.

**Review by jacobemery — APPROVED** [review]
Definitely need this.

**Pull request merged**
